---
- name: Restart multipathd
  service:
    name: multipathd
    state: restarted

- name: Restart k3s
  ansible.builtin.service:
    name: "{{ 'k3s' if inventory_hostname in groups['master'] else 'k3s-node' }}"
    state: restarted
  failed_when: false
